#ifndef QUASAR_STD_DATATYPES_H
#define QUASAR_STD_DATATYPES_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <quasar/core/dataprim.h>
#include <quasar/core/str.h>
#include <quasar/std/memory.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * datatypes.h — Quasar standard data structures API.
 *
 * All data structures are allocator-backed.  The allocator passed at
 * creation time owns all storage; individual element removal does not
 * reclaim memory — memory is released in bulk when the allocator is
 * freed (or when the structure's *_free() function is called, which
 * releases the backing storage but not the allocator itself).
 *
 * All data structures are value types (stack-allocated structs).
 * A zeroed struct represents an invalid / allocation-failed state.
 * Functions that take a pointer to a structure will safely no-op
 * when the pointer is NULL or the structure is in a zeroed state.
 *
 * Typed vector types (vec_ti32, vec_tf64, vec_tstr, etc.) are
 * generated by the DECLARE_VEC_TYPE macro.  Each typed vector is
 * a typedef for array_t with type-safe wrapper functions.
 */

/* ================================================================== */
/*  Generic Dynamic Array                                              */
/* ================================================================== */

/*
 * ── Creation ───────────────────────────────────────────────────────
 */

/*
 * Create a new dynamic array with the given element size.
 * The array starts with zero length and a default initial capacity.
 *
 * Returns a zeroed array_t if a is NULL or allocation fails.
 */
array_t array_new(Allocator *a, size_t element_size);

/*
 * Create a new dynamic array with the given element size and at least
 * the specified initial capacity.  Capacity is rounded up to the next
 * power of two.
 *
 * Returns a zeroed array_t if a is NULL or allocation fails.
 */
array_t array_with_capacity(Allocator *a, size_t element_size,
			    size_t capacity);

/*
 * ── Destruction ────────────────────────────────────────────────────
 */

/*
 * Free the array's backing storage and reset the struct to zero.
 * The allocator is NOT freed — the caller is responsible for the
 * allocator's lifetime.
 *
 * With arena/bump allocators, backing storage is NOT immediately
 * released — memory is reclaimed when the allocator is freed.
 * Safe to call on a zeroed array_t (no-op).
 */
void array_free(array_t *array);

/*
 * ── Inspection ─────────────────────────────────────────────────────
 */

/* Return the number of elements currently stored.  O(1). */
size_t array_len(array_t array);

/* Return the current capacity (max elements before reallocation).  O(1). */
size_t array_capacity(array_t array);

/* Return the element size this array was created with.  O(1). */
size_t array_element_size(array_t array);

/*
 * ── Element Access ─────────────────────────────────────────────────
 */

/*
 * Return a pointer to the element at index.  Behaviour is undefined
 * if index >= array_len(array).
 */
void *array_at(array_t array, size_t index);

/*
 * Return a const pointer to the element at index.  Behaviour is
 * undefined if index >= array_len(array).
 */
const void *array_at_const(array_t array, size_t index);

/*
 * ── Mutation ───────────────────────────────────────────────────────
 */

/*
 * Append element to the end of the array.  The element data is
 * memcpy'd into the array's storage.  If the array is at capacity,
 * it is grown automatically.
 *
 * No-op if array or element is NULL.
 */
void array_push(array_t *array, const void *element);

/*
 * Remove and copy the last element into out.  The array's length
 * is decremented; capacity is unchanged.
 *
 * No-op if array is NULL, out is NULL, or the array is empty.
 */
void array_pop(array_t *array, void *out);

/*
 * Insert element at index, shifting existing elements to the right.
 * O(n) where n = array_len(array) - index.  The array grows if at
 * capacity.
 *
 * Behaviour is undefined if index > array_len(array).
 * No-op if array or element is NULL.
 */
void array_insert(array_t *array, size_t index, const void *element);

/*
 * Remove the element at index, copying it into out, and shift
 * subsequent elements left.  O(n) where n = array_len(array) - index.
 *
 * No-op if array is NULL, out is NULL, or index >= array_len(array).
 */
void array_remove(array_t *array, size_t index, void *out);

/*
 * Remove all elements from the array (len = 0).  Capacity and
 * backing storage are retained so the array can be reused immediately.
 */
void array_clear(array_t *array);

/*
 * ── Capacity Management ────────────────────────────────────────────
 */

/*
 * Ensure the array has at least the requested capacity.  If capacity
 * is already sufficient, this is a no-op.  On success, existing
 * element pointers remain valid.  On failure, the array is unchanged.
 *
 * Returns true on success, false on allocation failure or if array
 * is NULL.
 */
bool array_reserve(array_t *array, size_t capacity);

/*
 * Resize the array to exactly length elements.  If length exceeds
 * the current capacity, new elements are zero-initialized.  If length
 * is less than array_len, trailing elements are discarded.
 *
 * Returns true on success, false on allocation failure or if array
 * is NULL.
 */
bool array_resize(array_t *array, size_t length);

/*
 * Shrink the backing storage to fit exactly the current number of
 * elements.  Existing element pointers are invalidated.
 *
 * NOTE: With arena/bump allocators, this allocates a new buffer
 * while the old buffer remains in the arena — total arena usage
 * may increase rather than decrease.  This function is most useful
 * with the dynamic allocator strategy.
 *
 * Returns true on success or if the array is already at minimum
 * capacity; false on allocation failure or if array is NULL.
 */
bool array_shrink_to_fit(array_t *array);

/* ================================================================== */
/*  Typed Vectors                                                      */
/* ================================================================== */

/*
 * DECLARE_VEC_TYPE(NAME, CTYPE)
 *
 * Generates a typed vector type `vec_t##NAME` and a family of
 * type-safe wrapper functions (`vec_##NAME##_*`) around the generic
 * array_t.  The generated functions are static inline — each
 * translation unit that includes this header gets its own copy.
 *
 * The generated API mirrors array_t exactly, with typed parameters
 * and return values instead of `void *`.  See the individual typed
 * vector sections below for usage.
 *
 * NAME is the short type suffix (e.g. i32, f64, str).
 * CTYPE is the C type stored in each element.
 */

#define DECLARE_VEC_TYPE(NAME, CTYPE)                                          \
	typedef array_t vec_t##NAME;                                           \
                                                                               \
	static inline vec_t##NAME vec_##NAME##_new(Allocator *a)                \
	{                                                                      \
		return array_new(a, sizeof(CTYPE));                            \
	}                                                                      \
                                                                               \
	static inline vec_t##NAME vec_##NAME##_with_capacity(                   \
	    Allocator *a, size_t capacity)                                     \
	{                                                                      \
		return array_with_capacity(a, sizeof(CTYPE), capacity);        \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_free(vec_t##NAME *v)                    \
	{                                                                      \
		array_free(v);                                                 \
	}                                                                      \
                                                                               \
	static inline size_t vec_##NAME##_len(vec_t##NAME v)                    \
	{                                                                      \
		return array_len(v);                                           \
	}                                                                      \
                                                                               \
	static inline size_t vec_##NAME##_capacity(vec_t##NAME v)               \
	{                                                                      \
		return array_capacity(v);                                      \
	}                                                                      \
                                                                               \
	static inline CTYPE vec_##NAME##_at(vec_t##NAME v, size_t index)        \
	{                                                                      \
		return *(const CTYPE *)array_at_const(v, index);               \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_push(vec_t##NAME *v, CTYPE val)         \
	{                                                                      \
		array_push(v, &val);                                           \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_pop(vec_t##NAME *v, CTYPE *out)         \
	{                                                                      \
		array_pop(v, out);                                             \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_insert(vec_t##NAME *v,                  \
					       size_t index, CTYPE val)         \
	{                                                                      \
		array_insert(v, index, &val);                                  \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_remove(vec_t##NAME *v,                  \
					       size_t index, CTYPE *out)      \
	{                                                                      \
		array_remove(v, index, out);                                   \
	}                                                                      \
                                                                               \
	static inline void vec_##NAME##_clear(vec_t##NAME *v)                   \
	{                                                                      \
		array_clear(v);                                                \
	}                                                                      \
                                                                               \
	static inline bool vec_##NAME##_reserve(vec_t##NAME *v,                 \
						size_t capacity)               \
	{                                                                      \
		return array_reserve(v, capacity);                             \
	}                                                                      \
                                                                               \
	static inline bool vec_##NAME##_resize(vec_t##NAME *v, size_t length)   \
	{                                                                      \
		return array_resize(v, length);                                \
	}                                                                      \
                                                                               \
	static inline bool vec_##NAME##_shrink_to_fit(vec_t##NAME *v)           \
	{                                                                      \
		return array_shrink_to_fit(v);                                 \
	}

/*
 * ── Integer Vectors ────────────────────────────────────────────────
 *
 * Usage:
 *   vec_ti32 numbers = vec_i32_new(arena);
 *   vec_i32_push(&numbers, 42);
 *   int32_t val = vec_i32_at(numbers, 0);
 */

DECLARE_VEC_TYPE(i8,  int8_t)
DECLARE_VEC_TYPE(i16, int16_t)
DECLARE_VEC_TYPE(i32, int32_t)
DECLARE_VEC_TYPE(i64, int64_t)

/*
 * ── Floating-Point Vectors ─────────────────────────────────────────
 *
 * Usage:
 *   vec_tf64 values = vec_f64_new(arena);
 *   vec_f64_push(&values, 3.14);
 *   double val = vec_f64_at(values, 0);
 */

DECLARE_VEC_TYPE(f32, float)
DECLARE_VEC_TYPE(f64, double)

/*
 * ── String Vector ──────────────────────────────────────────────────
 *
 * vec_tstr stores str_t elements.  Each str_t pushed into the vector
 * is stored by value (the struct is copied).  The vector does NOT own
 * the string data — strings remain owned by their original allocator.
 *
 * To create strings that share the vector's allocator lifetime:
 *   vec_tstr v = vec_str_new(arena);
 *   vec_str_push(&v, str_from(arena, "hello"));
 *
 * Usage:
 *   vec_tstr parts = vec_str_new(arena);
 *   vec_str_push(&parts, str_from(arena, "a"));
 *   vec_str_push(&parts, str_from(arena, "b"));
 *   str_t first = vec_str_at(parts, 0);  // "a"
 */

DECLARE_VEC_TYPE(str, str_t)

/*
 * ── Generic Dynamic Vector ─────────────────────────────────────────
 *
 * vec_v is a type alias for array_t, provided for users who prefer
 * the "vec" naming.  It is functionally identical to array_t.
 *
 * Usage:
 *   vec_v values = vec_new(arena, sizeof(MyStruct));
 *   MyStruct item = { ... };
 *   vec_push(&values, &item);
 */

typedef array_t vec_v;

static inline vec_v vec_new(Allocator *a, size_t element_size)
{
	return array_new(a, element_size);
}

static inline vec_v vec_with_capacity(Allocator *a, size_t element_size,
				      size_t capacity)
{
	return array_with_capacity(a, element_size, capacity);
}

static inline void vec_free(vec_v *v)           { array_free(v); }
static inline size_t vec_len(vec_v v)            { return array_len(v); }
static inline size_t vec_capacity(vec_v v)       { return array_capacity(v); }
static inline size_t vec_element_size(vec_v v)   { return array_element_size(v); }
static inline void *vec_at(vec_v v, size_t i)    { return array_at(v, i); }
static inline const void *vec_at_const(vec_v v, size_t i) { return array_at_const(v, i); }
static inline void vec_push(vec_v *v, const void *e)     { array_push(v, e); }
static inline void vec_pop(vec_v *v, void *out)          { array_pop(v, out); }
static inline void vec_insert(vec_v *v, size_t i, const void *e) { array_insert(v, i, e); }
static inline void vec_remove(vec_v *v, size_t i, void *out)     { array_remove(v, i, out); }
static inline void vec_clear(vec_v *v)                { array_clear(v); }
static inline bool vec_reserve(vec_v *v, size_t cap)  { return array_reserve(v, cap); }
static inline bool vec_resize(vec_v *v, size_t len)   { return array_resize(v, len); }
static inline bool vec_shrink_to_fit(vec_v *v)        { return array_shrink_to_fit(v); }

/* ================================================================== */
/*  Hash Map                                                           */
/* ================================================================== */

/*
 * ── Creation ───────────────────────────────────────────────────────
 */

/*
 * Create a new hash map with str_t keys and str_t values.
 * The map uses open addressing with linear probing and FNV-1a
 * hashing.  Initial capacity is a small power of two.
 *
 * Returns a zeroed map_t if a is NULL or allocation fails.
 */
map_t map_new(Allocator *a);

/*
 * Create a new hash map with at least the given initial capacity.
 * Capacity is rounded up to the next power of two.
 *
 * Returns a zeroed map_t if a is NULL or allocation fails.
 */
map_t map_new_with_capacity(Allocator *a, size_t capacity);

/*
 * ── Destruction ────────────────────────────────────────────────────
 */

/*
 * Free the map's entry table and reset the struct to zero.
 * The allocator is NOT freed.
 *
 * Safe to call on a zeroed map_t (no-op).
 */
void map_free(map_t *map);

/*
 * ── Inspection ─────────────────────────────────────────────────────
 */

/* Return the number of key-value pairs in the map.  O(1). */
size_t map_len(map_t map);

/* Return the current slot capacity.  O(1). */
size_t map_capacity(map_t map);

/*
 * ── Operations ─────────────────────────────────────────────────────
 */

/*
 * Insert a key-value pair into the map.  If the key already exists,
 * its value is replaced.  The key and value str_t values are copied
 * (shallow copy of the str_t struct — the string data is not copied).
 *
 * The map grows automatically when the load factor exceeds 0.75.
 * Existing key and value pointers may be invalidated after growth.
 * Keys and values stored before growth remain accessible through
 * map_get() which returns by value.
 *
 * Returns true on success, false on allocation failure.
 * No-op and returns false if map or key.data is NULL.
 */
bool map_insert(map_t *map, str_t key, str_t value);

/*
 * Retrieve the value associated with key.  Returns a zeroed str_t
 * ({NULL, 0}) if the key is not found or if key.data is NULL.
 */
str_t map_get(map_t map, str_t key);

/*
 * Return true if the map contains key.  Returns false if key is
 * not found or if key.data is NULL.
 */
bool map_contains(map_t map, str_t key);

/*
 * Remove the entry for key from the map.  A tombstone is left in
 * place to preserve the probe chain.  If the key is not found,
 * this is a no-op.
 *
 * No-op if map or key.data is NULL.
 */
void map_remove(map_t *map, str_t key);

/*
 * Remove all entries from the map (len = 0).  All slots are marked
 * as empty.  Capacity is retained.
 */
void map_clear(map_t *map);

/*
 * Ensure the map has at least the requested slot capacity.
 * If already sufficient, this is a no-op.
 *
 * Returns true on success, false on allocation failure or if map
 * is NULL.
 */
bool map_reserve(map_t *map, size_t capacity);

/* ================================================================== */
/*  Hash Functions                                                     */
/* ================================================================== */

/*
 * Standard hash functions for common types.  These produce a size_t
 * hash value suitable for use with hash tables.  The specific
 * algorithm (FNV-1a) is an implementation detail and may change.
 */

size_t hash_i8(int8_t v);
size_t hash_i16(int16_t v);
size_t hash_i32(int32_t v);
size_t hash_i64(int64_t v);

size_t hash_u8(uint8_t v);
size_t hash_u16(uint16_t v);
size_t hash_u32(uint32_t v);
size_t hash_u64(uint64_t v);

size_t hash_f32(float v);
size_t hash_f64(double v);

size_t hash_str(str_t s);
size_t hash_bytes(const void *data, size_t len);

/* ================================================================== */
/*  Singly Linked List                                                 */
/* ================================================================== */

/*
 * ── Creation ───────────────────────────────────────────────────────
 */

/*
 * Create a new singly linked list with the given element size.
 *
 * Returns a zeroed list_t if a is NULL or allocation fails.
 */
list_t list_new(Allocator *a, size_t element_size);

/*
 * ── Destruction ────────────────────────────────────────────────────
 */

/*
 * Free all list nodes and reset the struct to zero.
 * The allocator is NOT freed.
 *
 * Safe to call on a zeroed list_t (no-op).
 */
void list_free(list_t *list);

/*
 * ── Inspection ─────────────────────────────────────────────────────
 */

/* Return the number of nodes in the list.  O(1). */
size_t list_len(list_t list);

/*
 * ── Mutation ───────────────────────────────────────────────────────
 */

/*
 * Insert element at the front of the list.  O(1).
 * The element data is memcpy'd into the new node.
 *
 * No-op if list or element is NULL.
 */
void list_push_front(list_t *list, const void *element);

/*
 * Append element to the end of the list.  O(1).
 *
 * No-op if list or element is NULL.
 */
void list_push_back(list_t *list, const void *element);

/*
 * Remove and copy the front element into out.  O(1).
 *
 * No-op if list is NULL, out is NULL, or the list is empty.
 */
void list_pop_front(list_t *list, void *out);

/*
 * Remove and copy the back element into out.  O(n) —
 * singly linked lists must traverse to find the predecessor.
 *
 * No-op if list is NULL, out is NULL, or the list is empty.
 */
void list_pop_back(list_t *list, void *out);

/*
 * Detach all nodes from the list (len = 0).  Node memory is owned
 * by the allocator and reclaimed when the allocator is freed.  O(1).
 */
void list_clear(list_t *list);

/*
 * ── Node Access ────────────────────────────────────────────────────
 */

/*
 * Return the head node, or NULL if the list is empty.
 */
ListNode *list_head(list_t list);

/*
 * Return the tail node, or NULL if the list is empty.
 */
ListNode *list_tail(list_t list);

/*
 * Return a pointer to the data stored in node.  The data is owned
 * by the list — do not free it.
 */
void *list_node_data(ListNode *node);

/*
 * Return the successor of node, or NULL if node is the tail.
 */
ListNode *list_node_next(ListNode *node);

/* ================================================================== */
/*  Doubly Linked List                                                 */
/* ================================================================== */

/*
 * ── Creation ───────────────────────────────────────────────────────
 */

/*
 * Create a new doubly linked list with the given element size.
 *
 * Returns a zeroed dlist_t if a is NULL or allocation fails.
 */
dlist_t dlist_new(Allocator *a, size_t element_size);

/*
 * ── Destruction ────────────────────────────────────────────────────
 */

/*
 * Free all list nodes and reset the struct to zero.
 * The allocator is NOT freed.
 *
 * Safe to call on a zeroed dlist_t (no-op).
 */
void dlist_free(dlist_t *list);

/*
 * ── Inspection ─────────────────────────────────────────────────────
 */

/* Return the number of nodes in the list.  O(1). */
size_t dlist_len(dlist_t list);

/*
 * ── Mutation ───────────────────────────────────────────────────────
 */

/*
 * Insert at the front of the list.  O(1).
 *
 * No-op if list or element is NULL.
 */
void dlist_push_front(dlist_t *list, const void *element);

/*
 * Append to the end of the list.  O(1).
 *
 * No-op if list or element is NULL.
 */
void dlist_push_back(dlist_t *list, const void *element);

/*
 * Remove and copy the front element into out.  O(1).
 *
 * No-op if list is NULL, out is NULL, or the list is empty.
 */
void dlist_pop_front(dlist_t *list, void *out);

/*
 * Remove and copy the back element into out.  O(1).
 *
 * No-op if list is NULL, out is NULL, or the list is empty.
 */
void dlist_pop_back(dlist_t *list, void *out);

/*
 * Insert element before node in the list.  O(1).
 *
 * No-op if list, node, or element is NULL.
 */
void dlist_insert_before(dlist_t *list, DListNode *node,
			 const void *element);

/*
 * Insert element after node in the list.  O(1).
 *
 * No-op if list, node, or element is NULL.
 */
void dlist_insert_after(dlist_t *list, DListNode *node,
			const void *element);

/*
 * Remove node from the list, copying its data into out.  O(1).
 *
 * No-op if list or node is NULL.
 */
void dlist_remove(dlist_t *list, DListNode *node, void *out);

/*
 * Detach all nodes from the list (len = 0).  Node memory is owned
 * by the allocator and reclaimed when the allocator is freed.  O(1).
 */
void dlist_clear(dlist_t *list);

/*
 * ── Node Access ────────────────────────────────────────────────────
 */

/* Return the head node, or NULL if the list is empty. */
DListNode *dlist_head(dlist_t list);

/* Return the tail node, or NULL if the list is empty. */
DListNode *dlist_tail(dlist_t list);

/* Return a pointer to the data stored in node. */
void *dlist_node_data(DListNode *node);

/* Return the successor of node, or NULL if node is the tail. */
DListNode *dlist_node_next(DListNode *node);

/* Return the predecessor of node, or NULL if node is the head. */
DListNode *dlist_node_prev(DListNode *node);

/* ================================================================== */
/*  Ring Buffer                                                        */
/* ================================================================== */

/*
 * ── Creation ───────────────────────────────────────────────────────
 */

/*
 * Create a fixed-capacity ring buffer with the given element size
 * and capacity.  The buffer will never grow; ring_push() returns
 * false when full.
 *
 * Returns a zeroed ring_t if a is NULL or allocation fails.
 */
ring_t ring_new(Allocator *a, size_t element_size, size_t capacity);

/*
 * Create a dynamic ring buffer with the given element size.
 * The buffer grows automatically (by doubling) when full.
 *
 * Returns a zeroed ring_t if a is NULL or allocation fails.
 */
ring_t ring_new_dynamic(Allocator *a, size_t element_size);

/*
 * ── Destruction ────────────────────────────────────────────────────
 */

/*
 * Free the ring buffer's backing storage and reset the struct to
 * zero.  The allocator is NOT freed.
 *
 * Safe to call on a zeroed ring_t (no-op).
 */
void ring_free(ring_t *ring);

/*
 * ── Inspection ─────────────────────────────────────────────────────
 */

/* Return the number of elements currently stored.  O(1). */
size_t ring_len(ring_t ring);

/* Return the maximum number of elements that can be stored.  O(1). */
size_t ring_capacity(ring_t ring);

/* Return true if the buffer contains no elements. */
bool ring_is_empty(ring_t ring);

/* Return true if the buffer is at capacity. */
bool ring_is_full(ring_t ring);

/*
 * ── Operations ─────────────────────────────────────────────────────
 */

/*
 * Push element onto the back of the ring buffer.  The element data
 * is memcpy'd into the buffer.
 *
 * For fixed-capacity buffers: returns false when full.
 * For dynamic buffers: grows automatically, returns false only on
 * allocation failure.
 *
 * No-op and returns false if ring or element is NULL.
 */
bool ring_push(ring_t *ring, const void *element);

/*
 * Pop the front element from the ring buffer, copying it into out.
 *
 * Returns true on success, false if ring is NULL, out is NULL,
 * or the buffer is empty.
 */
bool ring_pop(ring_t *ring, void *out);

/*
 * Return a pointer to the front element (next to be popped).
 * The pointer is invalidated by ring_push() (dynamic buffer growth).
 *
 * Returns NULL if the buffer is empty.
 */
void *ring_front(ring_t ring);

/*
 * Return a pointer to the back element (most recently pushed).
 * The pointer is invalidated by ring_push() (dynamic buffer growth).
 *
 * Returns NULL if the buffer is empty.
 */
void *ring_back(ring_t ring);

/*
 * Remove all elements from the ring buffer (len = 0).
 * Backing storage is retained.
 */
void ring_clear(ring_t *ring);

#ifdef __cplusplus
}
#endif

#endif
